# Generated by Django 5.2.4 on 2025-10-17 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_faqcategory_faq_category'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='faq',
            unique_together={('question', 'answer')},
        ),
    ]
