from django.urls import path

from .views import (
    ContactListCreateView,
    ContactRetrieveUpdateDestroyView,
    FAQCategoryListCreateView,
    FAQCategoryRetrieveUpdateDestroyView,
    FAQListCreateView,
    FAQRetrieveUpdateDestroyView,
    NepdoraPopupFormListCreateView,
    NepdoraPopupFormRetrieveUpdateDestroyView,
    NepdoraTestimonialListCreateView,
    NepdoraTestimonialRetrieveUpdateDestroyView,
    NewsletterListCreateView,
    NewsletterRetrieveUpdateDestroyView,
    ShowcaseListCreateView,
    ShowcaseRetrieveUpdateDestroyView,
    VideoTestimonialListCreateView,
    VideoTestimonialRetrieveUpdateDestroyView,
)

urlpatterns = [
    path(
        "faq-category/",
        FAQCategoryListCreateView.as_view(),
        name="faq-category-list-create",
    ),
    path(
        "faq-category/<int:pk>/",
        FAQCategoryRetrieveUpdateDestroyView.as_view(),
        name="faq-category-retrieve-update-destroy",
    ),
    path("faq/", FAQListCreateView.as_view(), name="faq-list-create"),
    path(
        "faq/<int:pk>/",
        FAQRetrieveUpdateDestroyView.as_view(),
        name="faq-retrieve-update-destroy",
    ),
    path(
        "nepdora-testimonial/",
        NepdoraTestimonialListCreateView.as_view(),
        name="nepdora-testimonial-list-create",
    ),
    path(
        "nepdora-testimonial/<int:pk>/",
        NepdoraTestimonialRetrieveUpdateDestroyView.as_view(),
        name="nepdora-testimonial-retrieve-update-destroy",
    ),
    path(
        "nepdora-contact/",
        ContactListCreateView.as_view(),
        name="nepdora-contact-list-create",
    ),
    path(
        "nepdora-contact/<int:pk>/",
        ContactRetrieveUpdateDestroyView.as_view(),
        name="nepdora-contact-retrieve-update-destroy",
    ),
    path(
        "nepdora-newsletter/",
        NewsletterListCreateView.as_view(),
        name="nepdora-newsletter-list-create",
    ),
    path(
        "nepdora-newsletter/<int:pk>/",
        NewsletterRetrieveUpdateDestroyView.as_view(),
        name="nepdora-newsletter-retrieve-update-destroy",
    ),
    path(
        "showcase/",
        ShowcaseListCreateView.as_view(),
        name="showcase-list-create",
    ),
    path(
        "showcase/<int:pk>/",
        ShowcaseRetrieveUpdateDestroyView.as_view(),
        name="showcase-retrieve-update-destroy",
    ),
    path(
        "video-testimonial/",
        VideoTestimonialListCreateView.as_view(),
        name="video-testimonial-list-create",
    ),
    path(
        "video-testimonial/<int:pk>/",
        VideoTestimonialRetrieveUpdateDestroyView.as_view(),
        name="video-testimonial-retrieve-update-destroy",
    ),
    path(
        "nepdora-popup-form/",
        NepdoraPopupFormListCreateView.as_view(),
        name="nepdora-popup-form-list-create",
    ),
    path(
        "nepdora-popup-form/<int:pk>/",
        NepdoraPopupFormRetrieveUpdateDestroyView.as_view(),
        name="nepdora-popup-form-retrieve-update-destroy",
    ),
]
