# Generated by Django 5.2.4 on 2025-10-29 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logistics',
            name='is_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
