# Generated by Django 6.0 on 2026-04-19 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0015_client_sms_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSPurchaseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(help_text='Number of credits purchased')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('transaction_id', models.CharField(max_length=255, unique=True)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_purchases', to='tenants.client')),
            ],
        ),
        migrations.CreateModel(
            name='SMSSendHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_number', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('credits_used', models.IntegerField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_history', to='tenants.client')),
            ],
        ),
        migrations.CreateModel(
            name='SMSSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_credit', models.IntegerField(default=100)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='smssetting', to='tenants.client')),
            ],
        ),
    ]
