# Generated by Django 6.0 on 2026-04-19 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smspurchasehistory',
            name='client',
        ),
        migrations.RemoveField(
            model_name='smssendhistory',
            name='client',
        ),
        migrations.RemoveField(
            model_name='smssetting',
            name='client',
        ),
    ]
