# Generated by Django 6.0 on 2026-04-19 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_remove_smspurchasehistory_client_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SMSPurchaseHistory',
        ),
    ]
