# Generated by Django 5.1.7 on 2026-04-19 08:39

from django.db import migrations


def set_initial_credits(apps, schema_editor):
    SMSSetting = apps.get_model("sms", "SMSSetting")
    SMSSetting.objects.get_or_create(
        id=1,
        defaults={"sms_credit": 100}
    )

def reverse_initial_credits(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0003_delete_smspurchasehistory'),
    ]

    operations = [
        migrations.RunPython(set_initial_credits, reverse_initial_credits),
    ]
