# Generated by Django 6.0 on 2026-04-19 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0004_initial_sms_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='smssetting',
            name='delivery_sms_enabled',
            field=models.BooleanField(default=False, help_text='Enable automatic SMS notification when an order is marked as delivered.'),
        ),
        migrations.AddField(
            model_name='smssetting',
            name='delivery_sms_template',
            field=models.TextField(blank=True, default='Hi {{name}}, your order containing {{products}} worth Rs. {{total_amount}} has been delivered to {{location}}. Thank you for your purchase!', help_text='Template for delivery SMS. Available placeholders: {{name}}, {{products}}, {{total_amount}}, {{location}}', null=True),
        ),
    ]
