# Generated by Django 6.0 on 2026-04-19 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0005_add_delivery_sms_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smssetting',
            options={'verbose_name': 'SMS Setting', 'verbose_name_plural': 'SMS Settings'},
        ),
    ]
