# Generated by Django 5.2.4 on 2025-09-02 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='issue_category',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='reported_by',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='store',
        ),
        migrations.DeleteModel(
            name='IssueCategory',
        ),
        migrations.DeleteModel(
            name='Issue',
        ),
    ]
