# Generated by Django 5.2.4 on 2025-08-25 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_category_alter_product_options_product_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='alt_description',
        ),
    ]
