# Generated by Django 5.2.4 on 2025-09-01 11:22

import sales_crm.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_productimage_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.FileField(blank=True, null=True, storage=sales_crm.storage_backends.PublicMediaStorage(), upload_to='category_images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail_image',
            field=models.FileField(blank=True, null=True, storage=sales_crm.storage_backends.PublicMediaStorage(), upload_to='product_images'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.FileField(storage=sales_crm.storage_backends.PublicMediaStorage(), upload_to='product_images'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='image',
            field=models.FileField(blank=True, null=True, storage=sales_crm.storage_backends.PublicMediaStorage(), upload_to='sub_category_images'),
        ),
    ]
