# Generated by Django 5.2.4 on 2025-09-01 11:42

import sales_crm.storage_backends
import sales_crm.utils.file_size_validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_category_image_alter_product_thumbnail_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.FileField(blank=True, null=True, storage=sales_crm.storage_backends.PublicMediaStorage(), upload_to='category_images', validators=[sales_crm.utils.file_size_validator.file_size]),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail_image',
            field=models.FileField(blank=True, null=True, storage=sales_crm.storage_backends.PublicMediaStorage(), upload_to='product_images', validators=[sales_crm.utils.file_size_validator.file_size]),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.FileField(storage=sales_crm.storage_backends.PublicMediaStorage(), upload_to='product_images', validators=[sales_crm.utils.file_size_validator.file_size]),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='image',
            field=models.FileField(blank=True, null=True, storage=sales_crm.storage_backends.PublicMediaStorage(), upload_to='sub_category_images', validators=[sales_crm.utils.file_size_validator.file_size]),
        ),
    ]
