# Generated by Django 5.2.4 on 2025-09-01 11:48

import sales_crm.storage_backends
import sales_crm.utils.file_size_validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_category_image_alter_product_thumbnail_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.FileField(blank=True, null=True, storage=sales_crm.storage_backends.PublicMediaStorage(), upload_to='product_images', validators=[sales_crm.utils.file_size_validator.file_size]),
        ),
    ]
