# Generated by Django 5.2.4 on 2025-10-12 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_product_meta_description_product_meta_title_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductAttribute',
            new_name='ProductVariant',
        ),
        migrations.RenameModel(
            old_name='ProductAttributeValue',
            new_name='ProductVariantValue',
        ),
        migrations.RenameField(
            model_name='productvariantvalue',
            old_name='product_attribute',
            new_name='product_variant',
        ),
    ]
