# Generated by Django 5.2.4 on 2025-10-12 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_rename_productattribute_productvariant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariantvalue',
            name='available_stock',
        ),
        migrations.RemoveField(
            model_name='productvariantvalue',
            name='price',
        ),
        migrations.AlterField(
            model_name='productvariantvalue',
            name='value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
