# Generated by Django 5.2.4 on 2025-10-12 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_remove_productvariantvalue_available_stock_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='name',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='variant_images'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='product.product'),
        ),
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductOptionValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=100, null=True)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productoption')),
            ],
        ),
        migrations.AddField(
            model_name='productvariant',
            name='option_values',
            field=models.ManyToManyField(related_name='variants', to='product.productoptionvalue'),
        ),
        migrations.DeleteModel(
            name='ProductVariantValue',
        ),
    ]
