# Generated by Django 5.2.4 on 2025-10-12 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_remove_productvariant_name_productvariant_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
