# Generated by Django 5.2.4 on 2025-10-12 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_alter_product_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoption',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='option_values',
            field=models.ManyToManyField(blank=True, related_name='variants', to='product.productoptionvalue'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='stock',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
