# Generated by Django 5.2.4 on 2025-10-17 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_alter_product_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('name', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='subcategory',
            unique_together={('name', 'slug')},
        ),
    ]
