# Generated by Django 5.2.4 on 2025-10-17 08:19

import sales_crm.utils.file_size_validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_alter_product_thumbnail_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='thumbnail_image',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='product_images', validators=[sales_crm.utils.file_size_validator.file_size]),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='product_images', validators=[sales_crm.utils.file_size_validator.file_size]),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='variant_images'),
        ),
    ]
