# Generated by Django 5.2.4 on 2025-10-28 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fast_shipping',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
