# Generated by Django 5.2.4 on 2025-10-28 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_alter_product_warranty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='track_stock',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
