# Generated by Django 5.1.4 on 2026-03-23 10:14

import sales_crm.utils.file_size_validator
import sales_crm.utils.s3bucket
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_product_product_pro_status_48d769_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.FileField(blank=True, null=True, storage=sales_crm.utils.s3bucket.PublicMediaStorage(), upload_to='category_images', validators=[sales_crm.utils.file_size_validator.file_size]),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail_image',
            field=models.FileField(blank=True, max_length=255, null=True, storage=sales_crm.utils.s3bucket.PublicMediaStorage(), upload_to='product_images', validators=[sales_crm.utils.file_size_validator.file_size]),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.FileField(blank=True, max_length=255, null=True, storage=sales_crm.utils.s3bucket.PublicMediaStorage(), upload_to='product_images', validators=[sales_crm.utils.file_size_validator.file_size]),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='image',
            field=models.FileField(blank=True, null=True, storage=sales_crm.utils.s3bucket.PublicMediaStorage(), upload_to='variant_images'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='image',
            field=models.FileField(blank=True, null=True, storage=sales_crm.utils.s3bucket.PublicMediaStorage(), upload_to='sub_category_images', validators=[sales_crm.utils.file_size_validator.file_size]),
        ),
    ]
