# Generated by Django 6.0 on 2026-05-20 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0033_productoffer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('offer_type', models.CharField(choices=[('percentage', 'Percentage Discount'), ('fixed', 'Fixed Amount Discount'), ('bundle_price', 'Fixed Combo Price')], default='percentage', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('bundle_price', models.DecimalField(blank=True, decimal_places=2, help_text='The total flat price for the bundle of required products. (Only valid for cart level)', max_digits=10, null=True)),
                ('min_quantity', models.PositiveIntegerField(default=1, help_text='For item level: min quantity of product. For cart level: minimum total quantity to trigger offer.')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, help_text='Applicable categories for the offer.', related_name='offers', to='product.category')),
                ('products', models.ManyToManyField(blank=True, help_text='The specific products required or applicable for this offer.', related_name='offers', to='product.product')),
                ('sub_categories', models.ManyToManyField(blank=True, help_text='Applicable sub-categories for the offer.', related_name='offers', to='product.subcategory')),
            ],
        ),
        migrations.DeleteModel(
            name='ProductOffer',
        ),
    ]
