# Generated by Django 6.0 on 2026-05-20 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0034_offer_delete_productoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='bundle_price_type',
            field=models.CharField(choices=[('percentage', 'Percentage Discount'), ('fixed', 'Fixed Price (Flat Combo Price)')], default='fixed', help_text='Specifies if the bundle pricing is a percentage discount or a flat fixed combo price.', max_length=20),
        ),
    ]
