# Generated by Django 6.0 on 2026-05-20 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0035_offer_bundle_price_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='bundle_price',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='bundle_price_type',
        ),
        migrations.AlterField(
            model_name='offer',
            name='offer_type',
            field=models.CharField(choices=[('percentage', 'Percentage Discount'), ('fixed', 'Fixed Amount Discount')], default='percentage', max_length=20),
        ),
    ]
