# Generated by Django 6.0 on 2026-05-20 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0036_remove_offer_bundle_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='min_quantity',
        ),
    ]
