# Generated by Django 6.0 on 2026-05-20 11:35

import sales_crm.utils.file_size_validator
import sales_crm.utils.s3bucket
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0037_remove_offer_min_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, storage=sales_crm.utils.s3bucket.PublicMediaStorage(), upload_to='offer_images', validators=[sales_crm.utils.file_size_validator.file_size]),
        ),
    ]
