# Generated by Django 6.0 on 2026-06-08 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0039_offer_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='require_custom_image',
            field=models.BooleanField(default=False),
        ),
    ]
