# Generated by Django 6.0 on 2026-09-03 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0043_product_barcode'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subcategory',
            unique_together={('category', 'name'), ('category', 'slug')},
        ),
    ]
