# Generated by Django 5.2.4 on 2025-08-14 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_website_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='user',
        ),
    ]
