# Generated by Django 5.2.4 on 2025-08-21 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_website_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Website',
        ),
    ]
