# Generated by Django 5.2.4 on 2025-08-21 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_page_slug'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pagecomponent',
            unique_together={('page', 'component_type')},
        ),
    ]
