# Generated by Django 5.2.4 on 2025-08-21 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_pagecomponent_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecomponent',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='components', to='website.page'),
        ),
    ]
