# Generated by Django 5.2.4 on 2025-08-21 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_pagecomponent_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecomponent',
            name='component_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
