# Generated by Django 5.2.4 on 2025-08-21 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_alter_pagecomponent_component_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecomponent',
            name='order',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
