# Generated by Django 5.2.4 on 2025-08-21 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_alter_pagecomponent_order'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='page',
            unique_together={('title',)},
        ),
    ]
