# Generated by Django 5.2.4 on 2025-08-25 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_alter_page_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pagecomponent',
            unique_together=set(),
        ),
    ]
