# Generated by Django 5.2.4 on 2025-10-13 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_page_status_pagecomponent_status_theme_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='page',
            unique_together={('title', 'status')},
        ),
        migrations.AddField(
            model_name='page',
            name='published_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draft_version', to='website.page'),
        ),
        migrations.AddField(
            model_name='page',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.theme'),
        ),
        migrations.AddField(
            model_name='page',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pagecomponent',
            name='published_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draft_version', to='website.pagecomponent'),
        ),
        migrations.AddField(
            model_name='theme',
            name='published_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draft_version', to='website.theme'),
        ),
        migrations.AddField(
            model_name='theme',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
