# Generated by Django 5.2.4 on 2025-10-13 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_alter_page_unique_together_page_published_version_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pagecomponent',
            unique_together={('page', 'component_id', 'status')},
        ),
    ]
