# Generated by Django 5.2.4 on 2025-10-13 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_alter_pagecomponent_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pagecomponent',
            unique_together=set(),
        ),
    ]
