# Generated by Django 5.2.4 on 2025-10-31 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_alter_pagecomponent_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favicon', models.FileField(blank=True, null=True, upload_to='favicon')),
                ('logo', models.FileField(blank=True, null=True, upload_to='logo')),
            ],
        ),
    ]
