# Generated by Django 6.0 on 2026-01-28 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_siteconfig_address_siteconfig_email_siteconfig_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='business_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='business_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
