# Generated by Django 6.0 on 2026-02-19 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_siteconfig_business_details_siteconfig_business_name'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['status'], name='website_pag_status_56843b_idx'),
        ),
        migrations.AddIndex(
            model_name='pagecomponent',
            index=models.Index(fields=['status'], name='website_pag_status_f425d1_idx'),
        ),
        migrations.AddIndex(
            model_name='pagecomponent',
            index=models.Index(fields=['component_type'], name='website_pag_compone_79cc76_idx'),
        ),
        migrations.AddIndex(
            model_name='pagecomponent',
            index=models.Index(fields=['component_id'], name='website_pag_compone_f9d37d_idx'),
        ),
        migrations.AddIndex(
            model_name='theme',
            index=models.Index(fields=['status'], name='website_the_status_e0a47c_idx'),
        ),
    ]
