# Generated by Django 6.0 on 2026-03-25 06:49

import sales_crm.utils.s3bucket
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_page_website_pag_status_56843b_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='favicon',
            field=models.FileField(blank=True, null=True, storage=sales_crm.utils.s3bucket.PublicMediaStorage(), upload_to='favicon'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='logo',
            field=models.FileField(blank=True, null=True, storage=sales_crm.utils.s3bucket.PublicMediaStorage(), upload_to='logo'),
        ),
    ]
