# Generated by Django 6.0 on 2026-05-07 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_page_meta_description_page_meta_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='use_product_variant',
            field=models.BooleanField(default=False),
        ),
    ]
