# Generated by Django 6.0 on 2026-05-07 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_siteconfig_use_product_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfig',
            name='use_product_variant',
        ),
    ]
