# Generated by Django 6.0 on 2026-05-07 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_remove_siteconfig_use_product_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='use_product_variant',
            field=models.BooleanField(default=False),
        ),
    ]
