# Generated by Django 6.0 on 2026-05-13 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0029_siteconfig_use_product_variant'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['slug'], name='website_pag_slug_3346e2_idx'),
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['status', 'slug'], name='website_pag_status_d9d463_idx'),
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['published_version'], name='website_pag_publish_03e68c_idx'),
        ),
        migrations.AddIndex(
            model_name='pagecomponent',
            index=models.Index(fields=['page', 'status', 'order'], name='website_pag_page_id_63bde0_idx'),
        ),
        migrations.AddIndex(
            model_name='pagecomponent',
            index=models.Index(fields=['page', 'component_id'], name='website_pag_page_id_e335b2_idx'),
        ),
        migrations.AddIndex(
            model_name='pagecomponent',
            index=models.Index(fields=['component_type', 'status'], name='website_pag_compone_61efe3_idx'),
        ),
        migrations.AddIndex(
            model_name='pagecomponent',
            index=models.Index(fields=['published_version'], name='website_pag_publish_010cb6_idx'),
        ),
    ]
