# Generated by Django 6.0 on 2026-05-15 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0030_page_website_pag_slug_3346e2_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='map_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
