# Generated by Django 6.0 on 2026-05-24 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0031_siteconfig_map_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='tour',
            field=models.BooleanField(default=False),
        ),
    ]
