# Generated by Django 6.0 on 2026-05-29 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0032_siteconfig_tour'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='dynamic_qr',
            field=models.BooleanField(default=False),
        ),
    ]
