# Generated by Django 6.0 on 2026-06-01 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0033_siteconfig_dynamic_qr'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='enable_pasalbiz',
            field=models.BooleanField(default=False),
        ),
    ]
