# Generated by Django 6.0 on 2026-06-14 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0034_siteconfig_enable_pasalbiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='chat_enable',
            field=models.BooleanField(default=False),
        ),
    ]
