# Generated by Django 6.0 on 2026-06-21 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0035_siteconfig_chat_enable'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='dashboard_tour',
            field=models.BooleanField(default=False),
        ),
    ]
