# Generated by Django 6.0 on 2026-08-03 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0036_siteconfig_dashboard_tour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='enable_pasalbiz',
            field=models.BooleanField(default=True),
        ),
    ]
