# Generated by Django 6.0 on 2026-08-10 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0037_alter_siteconfig_enable_pasalbiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='pan_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='vat_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
