# Generated by Django 6.0 on 2026-08-12 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0038_siteconfig_pan_no_siteconfig_vat_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='enable_pasalbiz',
            field=models.BooleanField(default=False),
        ),
    ]
