# Generated by Django 6.0 on 2026-08-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0039_alter_siteconfig_enable_pasalbiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='onboarding_checklist',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='tour_checklist',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
