# Generated by Django 5.2.4 on 2025-11-05 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='duration_days',
            field=models.PositiveIntegerField(blank=True, help_text='Number of days this plan lasts', null=True),
        ),
    ]
