# Generated by Django 5.2.4 on 2025-11-05 07:35

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_pricing_duration_days'),
        ('tenants', '0002_client_paid_until_client_pricing_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_type', models.CharField(blank=True, choices=[('esewa', 'Esewa'), ('khalti', 'Khalti'), ('cash', 'Cash')], default='cash', max_length=50, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('started_on', models.DateField(default=datetime.date.today)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pricing.pricing')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_history', to='tenants.client')),
            ],
        ),
    ]
