# Generated by Django 5.2.4 on 2025-11-02 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_token', models.TextField(blank=True, null=True)),
                ('page_id', models.CharField(blank=True, max_length=255, null=True)),
                ('page_access_token', models.TextField(blank=True, null=True)),
                ('page_name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_enabled', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
