# Generated by Django 5.2.4 on 2025-11-02 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebook',
            name='app_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='facebook',
            name='app_secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
