# Generated by Django 5.2.4 on 2025-11-03 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0002_facebook_app_id_facebook_app_secret'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.CharField(max_length=255, unique=True)),
                ('participants', models.JSONField(blank=True, null=True)),
                ('snippet', models.TextField(blank=True, null=True)),
                ('updated_time', models.DateTimeField(blank=True, null=True)),
                ('messages', models.JSONField(blank=True, default=list, null=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='facebook.facebook')),
            ],
        ),
    ]
