# Generated by Django 5.2.4 on 2025-11-03 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0003_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='last_synced',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='messages',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
