# Generated by Django 5.2.4 on 2025-11-04 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0004_conversation_last_synced_alter_conversation_messages'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='facebook',
            unique_together={('page_id',)},
        ),
    ]
