# Generated by Django 5.2.4 on 2025-11-10 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0005_alter_facebook_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebook',
            name='conversations_next',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
