# Generated by Django 5.2.4 on 2025-11-10 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0006_facebook_conversations_next'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facebook',
            name='conversations_next',
        ),
    ]
