# Generated by Django 5.2.4 on 2025-12-02 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, null=True, unique=True)),
                ('default_fields', models.JSONField(default=dict, help_text="Default fields: {'name': {'type': 'text', 'required': true}, 'slug': {'type': 'text', 'required': false}, 'content': {'type': 'text', 'required': false}}")),
                ('fields', models.JSONField(default=list, help_text="Custom field definitions: [{'name': 'field_name', 'type': 'text', 'required': true, 'filterable': false}]")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Collection',
                'verbose_name_plural': 'Collections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CollectionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(help_text="Actual data values: {'field_name': 'value', ...}")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_instances', to='collection.collection')),
            ],
            options={
                'verbose_name': 'Collection Data',
                'verbose_name_plural': 'Collection Data',
                'ordering': ['-created_at'],
            },
        ),
    ]
