# Generated by Django 5.1.4 on 2026-03-23 10:14

import sales_crm.utils.s3bucket
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='photo',
            field=models.FileField(blank=True, null=True, storage=sales_crm.utils.s3bucket.PublicMediaStorage(), upload_to='team'),
        ),
    ]
