# Generated by Django 6.0 on 2026-05-28 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_alter_teammember_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
