# Generated by Django 5.2.4 on 2025-11-05 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_client_paid_until_client_pricing_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookPageTenantMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.client')),
            ],
            options={
                'db_table': 'public_facebook_page_map',
            },
        ),
    ]
