# Generated by Django 5.2.4 on 2025-11-06 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_facebookpagetenantmap'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookpagetenantmap',
            name='page_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
