# Generated by Django 5.2.4 on 2025-11-13 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_facebookpagetenantmap_page_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_template_account',
            field=models.BooleanField(default=False),
        ),
    ]
