# Generated by Django 5.2.4 on 2025-11-16 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_client_is_template_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='template_image',
            field=models.FileField(blank=True, null=True, upload_to='template_images'),
        ),
    ]
