# Generated by Django 5.2.4 on 2025-11-25 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_templatecategory_alter_client_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatecategory',
            name='website_type',
            field=models.CharField(blank=True, choices=[('ecommerce', 'ecommerce'), ('service', 'service')], max_length=10, null=True),
        ),
    ]
