# Generated by Django 5.1 on 2025-12-07 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_templatecategory_website_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='repo_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
