# Generated by Django 5.2.4 on 2025-12-29 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0010_client_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='preview_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
