# Generated by Django 5.1.4 on 2026-03-23 10:14

import sales_crm.utils.s3bucket
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0012_domain_created_at_domain_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='template_image',
            field=models.FileField(blank=True, null=True, storage=sales_crm.utils.s3bucket.PublicMediaStorage(), upload_to='template_images'),
        ),
    ]
