# Generated by Django 6.0 on 2026-04-19 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0013_alter_client_template_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='sms_credit',
            field=models.IntegerField(default=100),
        ),
    ]
