# Generated by Django 6.0 on 2026-04-19 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0014_client_sms_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='sms_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
