# Generated by Django 6.0 on 2026-04-19 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0015_client_sms_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='sms_credit',
        ),
        migrations.RemoveField(
            model_name='client',
            name='sms_enabled',
        ),
    ]
