# Generated by Django 6.0 on 2026-05-11 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0016_remove_client_sms_credit_remove_client_sms_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='sidebar_config',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
