# Generated by Django 5.1 on 2025-12-29 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_name', models.CharField(help_text='Name of the tenant/workspace', max_length=255)),
                ('user_prompt', models.TextField(help_text="The user's original request")),
                ('action_type', models.CharField(help_text='Type of action (e.g., analysis, generation)', max_length=50)),
                ('model_name', models.CharField(help_text='AI Model used (e.g., gemini-1.5-flash)', max_length=100)),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
