# Generated by Django 5.1.4 on 2026-03-13 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0011_client_preview_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='NepdoraPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('esewa', 'Esewa'), ('khalti', 'Khalti')], max_length=10, unique=True)),
                ('secret_key', models.CharField(blank=True, max_length=255, null=True)),
                ('merchant_code', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TenantCentralPaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('esewa', 'Esewa'), ('khalti', 'Khalti')], max_length=10)),
                ('pay_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_id', models.CharField(max_length=255)),
                ('products_purchased', models.JSONField(blank=True, default=dict, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('transferred', 'Transferred')], default='pending', max_length=20)),
                ('additional_info', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='central_payments', to='tenants.client')),
            ],
        ),
    ]
