# Generated by Django 5.1.4 on 2026-03-13 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nepdora_payment', '0001_initial'),
        ('tenants', '0011_client_preview_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantTransferHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transfer_date', models.DateTimeField()),
                ('reference_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_history', to='tenants.client')),
            ],
        ),
    ]
