# Generated by Django 5.1.4 on 2026-03-13 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nepdora_payment', '0002_tenanttransferhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantcentralpaymenthistory',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('received', 'Received')], default='pending', max_length=20),
        ),
    ]
