# Generated by Django 5.1.4 on 2026-03-13 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nepdora_payment', '0003_alter_tenantcentralpaymenthistory_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantcentralpaymenthistory',
            name='products_purchased',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
