# Generated by Django 6.0 on 2026-03-15 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nepdora_payment', '0004_alter_tenantcentralpaymenthistory_products_purchased'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenanttransferhistory',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
