# Generated by Django 6.0 on 2026-03-15 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nepdora_payment', '0005_tenanttransferhistory_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantcentralpaymenthistory',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
