# Generated by Django 6.0 on 2026-04-19 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nepdora_payment', '0006_tenantcentralpaymenthistory_is_read'),
        ('tenants', '0015_client_sms_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSPurchaseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(help_text='Number of credits purchased')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('transaction_id', models.CharField(max_length=255, unique=True)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_purchase_history', to='tenants.client')),
            ],
        ),
    ]
