# Generated by Django 6.0 on 2026-04-20 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nepdora_payment', '0007_smspurchasehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='smspurchasehistory',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('esewa', 'Esewa'), ('khalti', 'Khalti')], max_length=10, null=True),
        ),
    ]
