# Generated by Django 6.0 on 2026-04-20 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nepdora_payment', '0008_smspurchasehistory_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smspurchasehistory',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
