# Generated by Django 6.0 on 2026-05-13 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nepdora_payment', '0009_alter_smspurchasehistory_transaction_id'),
        ('tenants', '0017_client_sidebar_config'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tenantcentralpaymenthistory',
            index=models.Index(condition=models.Q(('is_read', False)), fields=['tenant'], name='tenant_central_unread_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantcentralpaymenthistory',
            index=models.Index(fields=['tenant', '-created_at'], name='nepdora_pay_tenant__12382a_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantcentralpaymenthistory',
            index=models.Index(fields=['transaction_id'], name='nepdora_pay_transac_8a6c45_idx'),
        ),
        migrations.AddIndex(
            model_name='tenanttransferhistory',
            index=models.Index(condition=models.Q(('is_read', False)), fields=['tenant'], name='tenant_transfer_unread_idx'),
        ),
        migrations.AddIndex(
            model_name='tenanttransferhistory',
            index=models.Index(fields=['tenant', '-transfer_date'], name='nepdora_pay_tenant__39fc8f_idx'),
        ),
    ]
