# Generated by Django 6.0 on 2026-03-09 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_contact_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
