# Generated by Django 6.0 on 2026-03-09 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
