# Generated by Django 6.0 on 2026-03-09 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_appointment_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='is_read',
        ),
    ]
