# Generated by Django 5.2.4 on 2025-07-15 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='store_name',
        ),
        migrations.RemoveField(
            model_name='storeprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('editor', 'Editor'), ('viewer', 'Viewer')], default='viewer', max_length=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='accounts.storeprofile'),
        ),
        migrations.AddField(
            model_name='storeprofile',
            name='store_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
