# Generated by Django 5.2.4 on 2025-07-16 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_storeprofile_business_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeprofile',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
