# Generated by Django 5.2.4 on 2025-08-12 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_storeprofile_whatsapp_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeprofile',
            name='document_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
