# Generated by Django 5.2.4 on 2025-08-18 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='frontend_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
