# Generated by Django 5.2.4 on 2025-08-18 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customuser_frontend_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='frontend_url',
            new_name='sub_domain',
        ),
    ]
