# Generated by Django 5.2.4 on 2025-08-19 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_rename_frontend_url_customuser_sub_domain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='store',
        ),
        migrations.AddField(
            model_name='storeprofile',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_stores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='storeprofile',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='stores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='invitation',
            unique_together={('email', 'store')},
        ),
    ]
