# Generated by Django 5.2.4 on 2025-11-19 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_customuser_is_first_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_onboarding_complete',
            field=models.BooleanField(default=False),
        ),
    ]
