# Generated by Django 5.2.4 on 2025-11-20 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_customuser_is_onboarding_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_first_login',
        ),
    ]
