# Generated by Django 5.2.4 on 2025-11-20 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_customuser_is_first_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_first_login',
            field=models.BooleanField(default=True),
        ),
    ]
