# Generated by Django 5.2.4 on 2025-11-24 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_customuser_is_first_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='website_type',
            field=models.CharField(choices=[('ecommerce', 'ecommerce'), ('service', 'service')], default='ecommerce', max_length=10),
        ),
    ]
