# Generated by Django 5.2.4 on 2025-11-24 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_customuser_website_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='website_type',
            field=models.CharField(blank=True, choices=[('ecommerce', 'ecommerce'), ('service', 'service')], max_length=10, null=True),
        ),
    ]
