# Generated by Django 5.1 on 2025-12-29 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_customuser_website_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_url', models.URLField()),
                ('active', models.BooleanField(default=True)),
                ('thumbnail_image', models.ImageField(blank=True, null=True, upload_to='template_thumbnails/')),
                ('alt_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
