# Generated by Django 5.1 on 2025-12-29 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_templateaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateaccount',
            name='name',
            field=models.CharField(default='Default Template', max_length=255),
        ),
        migrations.AddField(
            model_name='templateaccount',
            name='template_type',
            field=models.CharField(choices=[('ecommerce', 'ecommerce'), ('service', 'service')], default='ecommerce', max_length=10),
        ),
        migrations.AlterField(
            model_name='templateaccount',
            name='thumbnail_image',
            field=models.FileField(blank=True, null=True, upload_to='template_thumbnails/'),
        ),
    ]
