# Generated by Django 5.2.4 on 2025-12-29 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_templateaccount_name_templateaccount_template_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateaccount',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='templateaccount',
            name='preview_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
