# Generated by Django 5.2.4 on 2025-12-29 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_templateaccount_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TemplateAccount',
        ),
    ]
