# Generated by Django 6.0 on 2026-04-29 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_customuser_created_at_customuser_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='website_type',
            field=models.CharField(blank=True, choices=[('ecommerce', 'ecommerce'), ('service', 'service'), ('portfolio', 'portfolio')], max_length=10, null=True),
        ),
    ]
