# Generated by Django 6.0 on 2026-03-09 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0004_alter_popup_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='popupform',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
