# Generated by Django 6.0 on 2026-05-13 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0006_alter_bannerimage_image_alter_popup_image'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='popupform',
            index=models.Index(condition=models.Q(('is_read', False)), fields=['-created_at'], name='popupform_unread_idx'),
        ),
    ]
