# Generated by Django 6.0 on 2026-03-25 08:23

import sales_crm.utils.s3bucket
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nepdoratestimonial',
            name='image',
            field=models.FileField(blank=True, null=True, storage=sales_crm.utils.s3bucket.PublicMediaStorage(), upload_to='nepdora/testimonial/'),
        ),
    ]
