# Generated by Django 5.1.7 on 2026-04-19 05:54

import sales_crm.utils.s3bucket
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0006_showcase_videotestimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showcase',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=sales_crm.utils.s3bucket.PublicMediaStorage(), upload_to='showcase'),
        ),
        migrations.AlterField(
            model_name='videotestimonial',
            name='video',
            field=models.FileField(blank=True, null=True, storage=sales_crm.utils.s3bucket.PublicMediaStorage(), upload_to='video_testimonial'),
        ),
    ]
