# Generated by Django 5.1.7 on 2026-04-19 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0007_alter_showcase_image_alter_videotestimonial_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videotestimonial',
            name='video',
        ),
    ]
