# Generated by Django 5.1.7 on 2026-04-19 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0008_remove_videotestimonial_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videotestimonial',
            name='designation',
        ),
    ]
