# Generated by Django 5.1.7 on 2026-04-19 06:05

import sales_crm.utils.s3bucket
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0009_remove_videotestimonial_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showcase',
            name='image',
            field=models.FileField(blank=True, null=True, storage=sales_crm.utils.s3bucket.PublicMediaStorage(), upload_to='showcase'),
        ),
    ]
