# Generated by Django 6.0 on 2026-05-10 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0002_alter_customer_email_alter_customer_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partial'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='unpaid', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('booking_type', models.CharField(blank=True, max_length=100, null=True)),
                ('booking_name', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('customer_phone', models.CharField(blank=True, max_length=32, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('guests', models.PositiveIntegerField(blank=True, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('extras', models.JSONField(blank=True, help_text='Any additional data specific to the service', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='customer.customer')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='booking_boo_status_e01616_idx'), models.Index(fields=['payment_status'], name='booking_boo_payment_f1f0c0_idx'), models.Index(fields=['booking_type'], name='booking_boo_booking_149331_idx'), models.Index(fields=['customer_email'], name='booking_boo_custome_2675e6_idx'), models.Index(fields=['start_date'], name='booking_boo_start_d_830c09_idx'), models.Index(fields=['user'], name='booking_boo_user_id_d9826d_idx'), models.Index(fields=['status', 'payment_status'], name='booking_boo_status_518917_idx'), models.Index(fields=['booking_type', 'status'], name='booking_boo_booking_76e89e_idx')],
            },
        ),
    ]
