# Generated by Django 6.0 on 2026-05-13 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
        ('customer', '0002_alter_customer_email_alter_customer_password'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['-created_at'], name='booking_boo_created_ea78c6_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['end_date'], name='booking_boo_end_dat_9dd3c8_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['total_amount'], name='booking_boo_total_a_7a53e6_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user', '-created_at'], name='booking_boo_user_id_4f3fce_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['transaction_id'], name='booking_boo_transac_ea356d_idx'),
        ),
    ]
