# Generated by Django 6.0 on 2026-05-27 05:47

import sales_crm.utils.s3bucket
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_booking_boo_created_ea78c6_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='attachment',
            field=models.FileField(blank=True, help_text='Any supporting document (PDF, Word, etc.) related to this booking', null=True, storage=sales_crm.utils.s3bucket.PublicMediaStorage(), upload_to='bookings/attachments/'),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_screenshot',
            field=models.FileField(blank=True, help_text='Upload a screenshot or photo of the payment proof', null=True, storage=sales_crm.utils.s3bucket.PublicMediaStorage(), upload_to='bookings/payment_screenshots/'),
        ),
    ]
