# Generated by Django 6.0 on 2026-05-27 05:59

import sales_crm.utils.s3bucket
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_attachment_booking_payment_screenshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='attachment',
            field=models.FileField(blank=True, help_text='Any supporting document related to this booking', null=True, storage=sales_crm.utils.s3bucket.PublicMediaStorage(), upload_to='bookings/attachments/'),
        ),
    ]
