# Generated by Django 5.2.4 on 2025-09-01 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_meta_description_blog_meta_title_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='blog',
            unique_together={('title', 'slug')},
        ),
    ]
