# Generated by Django 5.2.4 on 2025-09-01 11:28

import sales_crm.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='thumbnail_image',
            field=models.FileField(blank=True, null=True, storage=sales_crm.storage_backends.PublicMediaStorage(), upload_to='blog/images/'),
        ),
    ]
