# Generated by Django 5.2.4 on 2025-09-01 11:42

import sales_crm.storage_backends
import sales_crm.utils.file_size_validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blog_thumbnail_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='thumbnail_image',
            field=models.FileField(blank=True, null=True, storage=sales_crm.storage_backends.PublicMediaStorage(), upload_to='blog/images/', validators=[sales_crm.utils.file_size_validator.file_size]),
        ),
    ]
