# Generated by Django 5.1.4 on 2026-03-23 10:14

import sales_crm.utils.file_size_validator
import sales_crm.utils.s3bucket
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blog_thumbnail_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='thumbnail_image',
            field=models.FileField(blank=True, null=True, storage=sales_crm.utils.s3bucket.PublicMediaStorage(), upload_to='blog/images/', validators=[sales_crm.utils.file_size_validator.file_size]),
        ),
    ]
