# Generated by Django 6.0 on 2026-05-13 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_blog_thumbnail_image'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['slug'], name='blog_blog_slug_d925e3_idx'),
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['created_at'], name='blog_blog_created_e997ae_idx'),
        ),
        migrations.AddIndex(
            model_name='tags',
            index=models.Index(fields=['slug'], name='blog_tags_slug_720acc_idx'),
        ),
    ]
