# Generated by Django 6.0 on 2026-07-30 11:49

import sales_crm.utils.file_size_validator
import sales_crm.utils.s3bucket
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_blog_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='thumbnail_image',
            field=models.FileField(blank=True, null=True, storage=sales_crm.utils.s3bucket.PublicMediaStorage(), upload_to='blog/category_images/', validators=[sales_crm.utils.file_size_validator.file_size]),
        ),
    ]
