# Generated by Django 5.2.4 on 2025-11-02 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('google_analytic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='googleanalytic',
            old_name='is_active',
            new_name='is_enabled',
        ),
    ]
