# Generated by Django 6.0 on 2026-09-01 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_pixel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaCommerce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
