# Generated by Django 5.2.4 on 2025-11-09 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0004_alter_templatepagecomponent_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatepagecomponent',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='components', to='template.template'),
        ),
    ]
