# Generated by Django 5.2.4 on 2025-11-16 06:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("template", "0005_templatepagecomponent_template"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TemplateTheme",
        ),
        migrations.DeleteModel(
            name="Template",
        ),
        migrations.DeleteModel(
            name="TemplatePage",
        ),
        migrations.DeleteModel(
            name="TemplatePageComponent",
        ),
    ]
