# Generated by Django 5.2.4 on 2025-10-17 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='service',
            unique_together={('title', 'slug')},
        ),
    ]
