# Generated by Django 5.1.4 on 2026-03-23 10:14

import sales_crm.utils.s3bucket
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_servicecategory_service_service_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='thumbnail_image',
            field=models.FileField(blank=True, null=True, storage=sales_crm.utils.s3bucket.PublicMediaStorage(), upload_to='service/thumbnail'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='thumbnail_image',
            field=models.FileField(blank=True, null=True, storage=sales_crm.utils.s3bucket.PublicMediaStorage(), upload_to='service/thumbnail'),
        ),
    ]
