# Generated by Django 6.0 on 2026-05-13 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_alter_service_thumbnail_image_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['slug'], name='service_ser_slug_1d1ace_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['service_category'], name='service_ser_service_6f609a_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['created_at'], name='service_ser_created_aac0e5_idx'),
        ),
        migrations.AddIndex(
            model_name='servicecategory',
            index=models.Index(fields=['slug'], name='service_ser_slug_279858_idx'),
        ),
    ]
