# Generated by Django 5.2.4 on 2025-09-03 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('open', 'Open'), ('in_progress', 'In Progress'), ('closed', 'Closed')], default='open', max_length=255),
        ),
    ]
