# Generated by Django 5.2.4 on 2025-11-27 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracking', '0003_alter_issue_reported_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='reported_by',
        ),
    ]
