# Generated by Django 6.0 on 2026-03-09 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracking', '0004_remove_issue_reported_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
