# Generated by Django 6.0 on 2026-03-09 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracking', '0005_issue_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='is_read',
        ),
    ]
