# Generated by Django 5.2.4 on 2025-11-28 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_pricing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourpricing',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
    ]
