# Generated by Django 6.0 on 2026-05-12 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_pricing', '0002_ourpricing_is_popular'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourpricing',
            name='unit',
            field=models.CharField(choices=[('month', 'Month'), ('year', 'Year'), ('once', 'Once')], default='month', max_length=100),
        ),
    ]
