# Generated by Django 6.0 on 2026-08-19 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nps_payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='npsconfig',
            name='is_sandbox',
            field=models.BooleanField(default=False),
        ),
    ]
