# Generated by Django 6.0 on 2026-09-09 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nps_payment', '0002_alter_npsconfig_is_sandbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='npstransaction',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
