# Generated by Django 5.2.4 on 2025-10-17 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtube',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
