# Generated by Django 5.2.4 on 2025-11-27 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0002_alter_youtube_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Youtube',
        ),
    ]
