from django.urls import path

from .views import (
    AdminProductListCreateView,
    BulkProductUploadView,
    CategoryListCreateView,
    CategoryRetrieveUpdateDestroyView,
    DownloadProductSampleTemplateView,
    OfferListCreateView,
    OfferRetrieveUpdateDestroyView,
    PricingMetricListCreateView,
    PricingMetricRetrieveUpdateDestroyView,
    ProductCompositionListCreateView,
    ProductCompositionRetrieveUpdateDestroyView,
    ProductExcelExportView,
    ProductImageListCreateView,
    ProductImageRetrieveUpdateDestroyView,
    ProductListCreateView,
    ProductRetrieveUpdateDestroyView,
    ProductReviewRetrieveUpdateDestroyView,
    ProductReviewView,
    ProductVariantListCreateView,
    ProductVariantRetrieveUpdateDestroyView,
    RelatedProductList,
    SubCategoryListCreateView,
    SubCategoryRetrieveUpdateDestroyView,
    WishlistListCreateView,
    WishlistRetrieveUpdateDestroyView,
)

urlpatterns = [
    path("product/", ProductListCreateView.as_view(), name="product-list-create"),
    path(
        "product-export/",
        ProductExcelExportView.as_view(),
        name="product-export",
    ),
    path(
        "admin-product/",
        AdminProductListCreateView.as_view(),
        name="admin-product-list-create",
    ),
    path(
        "product/<slug:slug>/",
        ProductRetrieveUpdateDestroyView.as_view(),
        name="product-retrieve-update-destroy",
    ),
    path(
        "product/<slug:slug>/related/",
        RelatedProductList.as_view(),
        name="related-product-list",
    ),
    path(
        "sub-category/",
        SubCategoryListCreateView.as_view(),
        name="sub-category-list-create",
    ),
    path(
        "sub-category/<slug:slug>/",
        SubCategoryRetrieveUpdateDestroyView.as_view(),
        name="sub-category-retrieve-update-destroy",
    ),
    path("category/", CategoryListCreateView.as_view(), name="category-list-create"),
    path(
        "category/<slug:slug>/",
        CategoryRetrieveUpdateDestroyView.as_view(),
        name="category-retrieve-update-destroy",
    ),
    path(
        "product-image/",
        ProductImageListCreateView.as_view(),
        name="product-image-list-create",
    ),
    path(
        "product-image/<int:pk>/",
        ProductImageRetrieveUpdateDestroyView.as_view(),
        name="product-image-retrieve-update-destroy",
    ),
    path(
        "product-review/",
        ProductReviewView.as_view(),
        name="product-review-list-create",
    ),
    path(
        "product-review/<int:id>/",
        ProductReviewRetrieveUpdateDestroyView.as_view(),
        name="product-review-retrieve-update-destroy",
    ),
    path(
        "product-variant/",
        ProductVariantListCreateView.as_view(),
        name="product-variant-list-create",
    ),
    path(
        "product-variant/<int:pk>/",
        ProductVariantRetrieveUpdateDestroyView.as_view(),
        name="product-variant-retrieve-update-destroy",
    ),
    path("wishlist/", WishlistListCreateView.as_view(), name="wishlist-list-create"),
    path(
        "wishlist/<int:id>/",
        WishlistRetrieveUpdateDestroyView.as_view(),
        name="wishlist-retrieve-update-destroy",
    ),
    path(
        "download-template/",
        DownloadProductSampleTemplateView.as_view(),
        name="download-product-template",
    ),
    path(
        "bulk-upload/",
        BulkProductUploadView.as_view(),
        name="bulk-product-upload",
    ),
    path(
        "pricing-metric/",
        PricingMetricListCreateView.as_view(),
        name="pricing-metric-list-create",
    ),
    path(
        "pricing-metric/<int:pk>/",
        PricingMetricRetrieveUpdateDestroyView.as_view(),
        name="pricing-metric-retrieve-update-destroy",
    ),
    path(
        "product-composition/",
        ProductCompositionListCreateView.as_view(),
        name="product-composition-list-create",
    ),
    path(
        "product-composition/<int:pk>/",
        ProductCompositionRetrieveUpdateDestroyView.as_view(),
        name="product-composition-retrieve-update-destroy",
    ),
    path(
        "offer/",
        OfferListCreateView.as_view(),
        name="offer-list-create",
    ),
    path(
        "offer/<int:pk>/",
        OfferRetrieveUpdateDestroyView.as_view(),
        name="offer-retrieve-update-destroy",
    ),
]
