# Generated by Django 6.0 on 2026-05-13 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_portfolio_category'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['slug'], name='portfolio_p_slug_a92ff2_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['category'], name='portfolio_p_categor_689e69_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['created_at'], name='portfolio_p_created_8773bc_idx'),
        ),
        migrations.AddIndex(
            model_name='portfoliocategory',
            index=models.Index(fields=['slug'], name='portfolio_p_slug_852728_idx'),
        ),
        migrations.AddIndex(
            model_name='portfoliotags',
            index=models.Index(fields=['slug'], name='portfolio_p_slug_787c17_idx'),
        ),
    ]
