# Generated by Django 5.2.4 on 2025-10-30 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('is_default', models.BooleanField(default=False)),
                ('default_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('cost_0_1kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('cost_1_2kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('cost_2_3kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('cost_3_5kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('cost_5_10kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('cost_above_10kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
            ],
        ),
    ]
