# Generated by Django 6.0 on 2026-06-25 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_charge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverycharge',
            name='coverage_area',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
