# Generated by Django 5.2.4 on 2025-10-16 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(blank=True, choices=[('esewa', 'Esewa'), ('khalti', 'Khalti')], max_length=10, null=True)),
                ('secret_key', models.CharField(blank=True, max_length=255, null=True)),
                ('merchant_code', models.CharField(blank=True, max_length=255, null=True)),
                ('is_enabled', models.BooleanField(default=False)),
            ],
        ),
    ]
