# Generated by Django 5.2.4 on 2025-10-16 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_gateway', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('esewa', 'Esewa'), ('khalti', 'Khalti')], default=1, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
