# Generated by Django 6.0 on 2026-03-15 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_gateway', '0004_alter_paymenthistory_products_purchased'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
