# Generated by Django 6.0 on 2026-05-29 08:03

import sales_crm.utils.s3bucket
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_gateway', '0005_paymenthistory_is_read'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentQR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('esewa', 'Esewa'), ('khalti', 'Khalti'), ('Bank', 'Bank'), ('Fonepay', 'Fonepay')], max_length=10, unique=True)),
                ('qr', models.FileField(blank=True, null=True, storage=sales_crm.utils.s3bucket.PublicMediaStorage(), upload_to='payment_qr')),
                ('is_enabled', models.BooleanField(default=True)),
            ],
        ),
    ]
