# Generated by Django 6.0 on 2026-06-04 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
