# Generated by Django 6.0 on 2026-05-13 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nepdora_blog', '0003_alter_blog_thumbnail_image'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['slug'], name='nepdora_blo_slug_b78700_idx'),
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['category'], name='nepdora_blo_categor_a03343_idx'),
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['created_at'], name='nepdora_blo_created_99ecd2_idx'),
        ),
        migrations.AddIndex(
            model_name='blogcategory',
            index=models.Index(fields=['slug'], name='nepdora_blo_slug_ebab6e_idx'),
        ),
        migrations.AddIndex(
            model_name='tags',
            index=models.Index(fields=['slug'], name='nepdora_blo_slug_4269bb_idx'),
        ),
    ]
