# Generated by Django 5.2.4 on 2025-10-28 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_orderitem_variant_alter_orderitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('cod', 'Cash On Delivery'), ('khalti', 'Khalti'), ('esewa', 'Esewa')], default='cod', max_length=20),
        ),
    ]
