# Generated by Django 5.2.4 on 2025-10-28 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_order_latitude_order_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_manual',
            field=models.BooleanField(default=False),
        ),
    ]
