# Generated by Django 5.2.4 on 2025-10-29 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dash_tracking_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
