# Generated by Django 5.2.4 on 2025-10-29 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_order_promo_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dash_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
