# Generated by Django 5.2.4 on 2025-10-30 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_order_delivery_charge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='dash_location',
            new_name='city',
        ),
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
