# Generated by Django 6.0 on 2026-03-09 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_order_order_order_status_2f1723_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
