# Generated by Django 6.0 on 2026-03-09 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_order_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_read',
        ),
    ]
