# Generated by Django 5.1.4 on 2026-03-16 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_remove_order_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('cod', 'Cash On Delivery'), ('khalti', 'Khalti'), ('esewa', 'Esewa'), ('cash', 'Cash')], default='cod', max_length=20),
        ),
    ]
