# Generated by Django 5.1.4 on 2026-03-16 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0022_alter_order_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pos_order',
            field=models.BooleanField(default=False),
        ),
    ]
