# Generated by Django 6.0 on 2026-05-13 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customer_email_alter_customer_password'),
        ('order', '0023_order_pos_order'),
        ('promo_code', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer', '-created_at'], name='order_order_custome_a2521b_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', '-created_at'], name='order_order_status_f574c5_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['is_manual', '-created_at'], name='order_order_is_manu_54a1d6_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['pos_order', '-created_at'], name='order_order_pos_ord_b4dbb2_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at', 'status'], name='order_order_created_b5abb7_idx'),
        ),
    ]
