# Generated by Django 6.0 on 2026-05-20 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0024_order_order_order_custome_a2521b_idx_and_more'),
        ('product', '0034_offer_delete_productoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='product.offer'),
        ),
        migrations.AddField(
            model_name='order',
            name='offer_discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
