# Generated by Django 6.0 on 2026-05-20 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0025_order_offer_order_offer_discount'),
        ('product', '0034_offer_delete_productoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='product.offer'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='offer_discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
