# Generated by Django 6.0 on 2026-05-29 08:03

import sales_crm.utils.s3bucket
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0026_orderitem_offer_orderitem_offer_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='attachment',
            field=models.FileField(blank=True, null=True, storage=sales_crm.utils.s3bucket.PublicMediaStorage(), upload_to='order/attachment'),
        ),
    ]
