# Generated by Django 6.0 on 2026-05-29 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0027_order_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('cod', 'Cash On Delivery'), ('khalti', 'Khalti'), ('esewa', 'Esewa'), ('cash', 'Cash'), ('Fonepay', 'Fonepay'), ('Bank', 'Bank')], default='cod', max_length=20),
        ),
    ]
