# Generated by Django 6.0 on 2026-05-31 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0028_alter_order_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cash_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='online_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='online_payment_type',
            field=models.CharField(blank=True, choices=[('khalti', 'Khalti'), ('esewa', 'Esewa'), ('Fonepay', 'Fonepay'), ('Bank', 'Bank')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('cod', 'Cash On Delivery'), ('khalti', 'Khalti'), ('esewa', 'Esewa'), ('cash', 'Cash'), ('Fonepay', 'Fonepay'), ('Bank', 'Bank'), ('split', 'Split Payment')], default='cod', max_length=20),
        ),
    ]
