# Generated by Django 6.0 on 2026-06-01 10:05

import sales_crm.utils.s3bucket
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0029_order_cash_amount_order_online_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='additional_file',
            field=models.FileField(blank=True, null=True, storage=sales_crm.utils.s3bucket.PublicMediaStorage(), upload_to='order/additional_file'),
        ),
    ]
