# Generated by Django 6.0 on 2026-06-08 04:40

import django.db.models.deletion
import sales_crm.utils.s3bucket
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0030_order_additional_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(storage=sales_crm.utils.s3bucket.PublicMediaStorage(), upload_to='order_item/images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='order.orderitem')),
            ],
        ),
    ]
