# Generated by Django 6.0 on 2026-06-17 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0031_orderitemimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemimage',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
