# Generated by Django 6.0 on 2026-08-19 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0032_orderitemimage_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='online_payment_type',
            field=models.CharField(blank=True, choices=[('khalti', 'Khalti'), ('esewa', 'Esewa'), ('nps', 'NPS Gateway'), ('Fonepay', 'Fonepay'), ('Bank', 'Bank')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('cod', 'Cash On Delivery'), ('khalti', 'Khalti'), ('esewa', 'Esewa'), ('nps', 'NPS Gateway'), ('cash', 'Cash'), ('Fonepay', 'Fonepay'), ('Bank', 'Bank'), ('split', 'Split Payment')], default='cod', max_length=20),
        ),
    ]
